import { MainState } from './main-types';
import { DelegatorState } from './delegator-types';
import { GuardiansState } from './guardians-types';
import { OverviewState } from './overview-types';

export const types = {
    SET_DATA_TO_GLOBAL_REDUCER: 'SET_DATA_TO_GLOBAL_REDUCER',
    SET_INITIAL_CONFIG: 'SET_INITIAL_CONFIG',
 

    DELEGATOR: {
        DELEGATOR_DETAIL_HYDRATE: 'DELEGATOR_DETAIL_HYDRATE',
        SELECT_DELEGATOR_DETAIL: 'SELECT_DELEGATOR_DETAIL',
        DELEGATOR_CURRENT_REQUEST: 'DELEGATOR_CURRENT_REQUEST',
        DELEGATOR_CURRENT_SUCCESS: 'DELEGATOR_CURRENT_SUCCESS',
        DELEGATOR_CURRENT_FAILURE: 'DELEGATOR_CURRENT_FAILURE',
        SELECT_DELEGATOR_HISTORY: 'SELECT_DELEGATOR_HISTORY',
        DELEGATOR_HISTORY_REQUEST: 'DELEGATOR_HISTORY_REQUEST',
        DELEGATOR_HISTORY_SUCCESS: 'DELEGATOR_HISTORY_SUCCESS',
        DELEGATOR_HISTORY_FAILURE: 'DELEGATOR_HISTORY_FAILURE',
        DELEGATOR_HISTORY_CANCELLED: 'DELEGATOR_HISTORY_CANCELLED',
        SET_DELEGATOR: 'SET_DELEGATOR',
        DELEGATOR_NOT_FOUND: 'DELEGATOR_NOT_FOUND',
        DELEGATOR_LOADING: 'DELEGATOR_LOADING',
        CLEAR_DELEGATOR: 'CLEAR_DELEGATOR',
        SET_DELEGATOR_CHART_DATA: 'SET_DELEGATOR_CHART_DATA',
        RESET_DELEGATOR: 'RESET_DELEGATOR'
    },
    GUARDIAN: {
        GUARDIAN_DETAIL_HYDRATE: 'GUARDIAN_DETAIL_HYDRATE',
        SELECT_GUARDIAN_DETAIL: 'SELECT_GUARDIAN_DETAIL',
        GUARDIAN_CURRENT_REQUEST: 'GUARDIAN_CURRENT_REQUEST',
        GUARDIAN_CURRENT_SUCCESS: 'GUARDIAN_CURRENT_SUCCESS',
        GUARDIAN_CURRENT_FAILURE: 'GUARDIAN_CURRENT_FAILURE',
        SELECT_GUARDIAN_HISTORY: 'SELECT_GUARDIAN_HISTORY',
        GUARDIAN_HISTORY_REQUEST: 'GUARDIAN_HISTORY_REQUEST',
        GUARDIAN_HISTORY_SUCCESS: 'GUARDIAN_HISTORY_SUCCESS',
        GUARDIAN_HISTORY_FAILURE: 'GUARDIAN_HISTORY_FAILURE',
        GUARDIAN_HISTORY_CANCELLED: 'GUARDIAN_HISTORY_CANCELLED',
        GUARDIAN_DELEGATORS_REQUEST: 'GUARDIAN_DELEGATORS_REQUEST',
        GUARDIAN_DELEGATORS_SUCCESS: 'GUARDIAN_DELEGATORS_SUCCESS',
        GUARDIAN_DELEGATORS_FAILURE: 'GUARDIAN_DELEGATORS_FAILURE',
        GUARDIAN_DELEGATORS_CANCELLED: 'GUARDIAN_DELEGATORS_CANCELLED',
        SET_GUARDIANS: 'SET_GUARDIANS',
        SET_GUARDIAN: 'SET_GUARDIAN',
        GUARDIAN_NOT_FOUND: 'GUARDIAN_NOT_FOUND',
        GUARDIAN_LOADING: 'GUARDIAN_LOADING',
        SET_GUARDIAN_CHART_DATA: 'SET_GUARDIAN_CHART_DATA',
        RESET_GUARDIAN: 'RESET_GUARDIAN'
    },
    OVERVIEW: {
        SET_OVERVIEW: 'SET_OVERVIEW',
        SET_OVERVIEW_IS_LOADING: 'SET_OVERVIEW_IS_LOADING',
        SET_STAKE_CHART_DATA: 'SET_STAKE_CHART_DATA',
        SET_WEIGHTS_CHART_DATA: 'SET_WEIGHTS_CHART_DATA'
    }
};

export interface AppState {
    main: MainState;
    delegator: DelegatorState;
    guardians: GuardiansState;
    overview: OverviewState;
}
